version: "3.8"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    volumes:
      - /hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "9870:9870"
    networks:
      - no-internet

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    volumes:
      - /hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    links:
      - namenode
    networks:
      - no-internet

  hive-server:
    build:
      context: .
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    links:
      - datanode
      - hive-metastore
    networks:
      - no-internet
    ports:
      - "10000:10000"

  hive-metastore:
    build:
      context: .
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    links:
      - hive-metastore-postgresql
      - namenode
    networks:
      - no-internet
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"

  hive-metastore-postgresql:
    build:
      context: https://github.com/big-data-europe/docker-hive-metastore-postgresql.git#3.1.0
    networks:
      - no-internet

networks:
  no-internet: # blocks traffic from inside docker to host
    name: no-internet
    driver: bridge
    internal: true

  internet:
    name: internet
    driver: bridge
